#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly PROG=encoders2mopidy
readonly TARGET_HOST=pi@$1
readonly TARGET_PATH=/home/pi/code/${PROG}
readonly TARGET_ARCH=arm-unknown-linux-gnueabihf

#  use these 2 lines for release build...
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/${PROG}
time cargo build --release --target=${TARGET_ARCH}

#  ... and these 2 lines for debug build
#readonly SOURCE_PATH=./target/${TARGET_ARCH}/debug/${PROG}
#cargo build --target=${TARGET_ARCH}

rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} ${TARGET_PATH}